name: Run Unit Tests

on: [pull_request]

jobs:
  run-unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - run: npm ci --force

      - run: npm run test
        env:
          ENVIRONMENT_TYPE: "develop"
          BRDOC_ADMIN_USERNAME: "integration.bot"
          BRDOC_ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
          BRDOC_USERNAME: "integration.bot"
          BRDOC_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
